# Generated by Django 2.1 on 2018-11-23 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20181124_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absentees',
            field=models.ManyToManyField(blank=True, to='attendance.Students'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
