# Generated by Django 2.1 on 2018-11-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20181124_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.NSSUnits'),
            preserve_default=False,
        ),
    ]
